-- 코드를 입력하세요
SELECT FR.PRODUCT_ID, FR.PRODUCT_NAME, (FR.PRICE * FO.TOTAL_AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT FR
JOIN (SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL_AMOUNT
FROM FOOD_ORDER
WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
GROUP BY PRODUCT_ID) FO ON FR.PRODUCT_ID = FO.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FR.PRODUCT_ID 

# SELECT *, SUM(AMOUNT) AS TOTAL_AMOUNT
# FROM FOOD_ORDER
# WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
# GROUP BY PRODUCT_ID