-- 코드를 입력하세요
SELECT
    UGB.TITLE,
    UGB.BOARD_ID,
    UGR.REPLY_ID,
    UGR.WRITER_ID,
    UGR.CONTENTS,
    DATE_FORMAT(UGR.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD UGB JOIN USED_GOODS_REPLY UGR ON UGB.BOARD_ID = UGR.BOARD_ID
WHERE
    UGB.CREATED_DATE BETWEEN STR_TO_DATE('2022-10-01', '%Y-%m-%d') AND STR_TO_DATE('2022-10-31', '%Y-%m-%d')
ORDER BY UGR.CREATED_DATE, UGB.TITLE